package com.ascent.dao;

import com.ascent.bean.Ntype;
import com.ascent.bean.NtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    long countByExample(NtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int deleteByExample(NtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int insert(Ntype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int insertSelective(Ntype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    List<Ntype> selectByExample(NtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    Ntype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ntype record, @Param("example") NtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ntype record, @Param("example") NtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ntype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ntype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ntype record);
}