package com.ascent.dao;

import com.ascent.bean.Usr;
import com.ascent.bean.UsrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    long countByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int deleteByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int insert(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int insertSelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    List<Usr> selectByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    Usr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usr record);
}