package com.ascent.bean;

public class Authorization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.columnid
     *
     * @mbg.generated
     */
    private Integer columnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.auth
     *
     * @mbg.generated
     */
    private Integer auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.init
     *
     * @mbg.generated
     */
    private Integer init;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.authorize
     *
     * @mbg.generated
     */
    private Integer authorize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.id
     *
     * @return the value of authorization.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.id
     *
     * @param id the value for authorization.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.columnid
     *
     * @return the value of authorization.columnid
     *
     * @mbg.generated
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.columnid
     *
     * @param columnid the value for authorization.columnid
     *
     * @mbg.generated
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.auth
     *
     * @return the value of authorization.auth
     *
     * @mbg.generated
     */
    public Integer getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.auth
     *
     * @param auth the value for authorization.auth
     *
     * @mbg.generated
     */
    public void setAuth(Integer auth) {
        this.auth = auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.init
     *
     * @return the value of authorization.init
     *
     * @mbg.generated
     */
    public Integer getInit() {
        return init;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.init
     *
     * @param init the value for authorization.init
     *
     * @mbg.generated
     */
    public void setInit(Integer init) {
        this.init = init;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.authorize
     *
     * @return the value of authorization.authorize
     *
     * @mbg.generated
     */
    public Integer getAuthorize() {
        return authorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.authorize
     *
     * @param authorize the value for authorization.authorize
     *
     * @mbg.generated
     */
    public void setAuthorize(Integer authorize) {
        this.authorize = authorize;
    }
}