package com.ascent.bean;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.deptid
     *
     * @mbg.generated
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.checkstatus
     *
     * @mbg.generated
     */
    private Integer checkstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.crosscolumn
     *
     * @mbg.generated
     */
    private Integer crosscolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.crossstatus
     *
     * @mbg.generated
     */
    private Integer crossstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.picturepath
     *
     * @mbg.generated
     */
    private String picturepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.publishtime
     *
     * @mbg.generated
     */
    private Date publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.crosspubtime
     *
     * @mbg.generated
     */
    private Date crosspubtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.preface
     *
     * @mbg.generated
     */
    private Integer preface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.deptid
     *
     * @return the value of news.deptid
     *
     * @mbg.generated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.deptid
     *
     * @param deptid the value for news.deptid
     *
     * @mbg.generated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.type
     *
     * @return the value of news.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.type
     *
     * @param type the value for news.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.checkstatus
     *
     * @return the value of news.checkstatus
     *
     * @mbg.generated
     */
    public Integer getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.checkstatus
     *
     * @param checkstatus the value for news.checkstatus
     *
     * @mbg.generated
     */
    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.crosscolumn
     *
     * @return the value of news.crosscolumn
     *
     * @mbg.generated
     */
    public Integer getCrosscolumn() {
        return crosscolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.crosscolumn
     *
     * @param crosscolumn the value for news.crosscolumn
     *
     * @mbg.generated
     */
    public void setCrosscolumn(Integer crosscolumn) {
        this.crosscolumn = crosscolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.crossstatus
     *
     * @return the value of news.crossstatus
     *
     * @mbg.generated
     */
    public Integer getCrossstatus() {
        return crossstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.crossstatus
     *
     * @param crossstatus the value for news.crossstatus
     *
     * @mbg.generated
     */
    public void setCrossstatus(Integer crossstatus) {
        this.crossstatus = crossstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.picturepath
     *
     * @return the value of news.picturepath
     *
     * @mbg.generated
     */
    public String getPicturepath() {
        return picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.picturepath
     *
     * @param picturepath the value for news.picturepath
     *
     * @mbg.generated
     */
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath == null ? null : picturepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.publishtime
     *
     * @return the value of news.publishtime
     *
     * @mbg.generated
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.publishtime
     *
     * @param publishtime the value for news.publishtime
     *
     * @mbg.generated
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.crosspubtime
     *
     * @return the value of news.crosspubtime
     *
     * @mbg.generated
     */
    public Date getCrosspubtime() {
        return crosspubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.crosspubtime
     *
     * @param crosspubtime the value for news.crosspubtime
     *
     * @mbg.generated
     */
    public void setCrosspubtime(Date crosspubtime) {
        this.crosspubtime = crosspubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.preface
     *
     * @return the value of news.preface
     *
     * @mbg.generated
     */
    public Integer getPreface() {
        return preface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.preface
     *
     * @param preface the value for news.preface
     *
     * @mbg.generated
     */
    public void setPreface(Integer preface) {
        this.preface = preface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.status
     *
     * @return the value of news.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.status
     *
     * @param status the value for news.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.userid
     *
     * @return the value of news.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.userid
     *
     * @param userid the value for news.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}