package com.ascent.bean;

public class NewsWithBLOBs extends News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.checkopinion
     *
     * @mbg.generated
     */
    private String checkopinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.checkopinion2
     *
     * @mbg.generated
     */
    private String checkopinion2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.checkopinion
     *
     * @return the value of news.checkopinion
     *
     * @mbg.generated
     */
    public String getCheckopinion() {
        return checkopinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.checkopinion
     *
     * @param checkopinion the value for news.checkopinion
     *
     * @mbg.generated
     */
    public void setCheckopinion(String checkopinion) {
        this.checkopinion = checkopinion == null ? null : checkopinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.checkopinion2
     *
     * @return the value of news.checkopinion2
     *
     * @mbg.generated
     */
    public String getCheckopinion2() {
        return checkopinion2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.checkopinion2
     *
     * @param checkopinion2 the value for news.checkopinion2
     *
     * @mbg.generated
     */
    public void setCheckopinion2(String checkopinion2) {
        this.checkopinion2 = checkopinion2 == null ? null : checkopinion2.trim();
    }
}