package com.ascent.bean;

public class Ntype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntype.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntype.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntype.subType
     *
     * @mbg.generated
     */
    private String subtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntype.id
     *
     * @return the value of ntype.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntype.id
     *
     * @param id the value for ntype.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntype.type
     *
     * @return the value of ntype.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntype.type
     *
     * @param type the value for ntype.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntype.subType
     *
     * @return the value of ntype.subType
     *
     * @mbg.generated
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntype.subType
     *
     * @param subtype the value for ntype.subType
     *
     * @mbg.generated
     */
    public void setSubtype(String subtype) {
        this.subtype = subtype == null ? null : subtype.trim();
    }
}